server:
  port: 8081
  servlet:
    context-path: /staff


# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staff-work?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 5 #最大连接数
        max-wait: 3s #最大等待时间
        min-idle: 4
        max-idle: 8
    timeout: 5000 #(ms)
    database: 5
    password: 123456

  # 文件上传设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

file:
  common:
    ## window下系统访问路径
    uploadWindow: E:\毕业设计\project\staff-work\upload\img\
    ## linux下系统范文路径
    uploadLinux: /user/img/

# mybatis配置
mybatis:
  mapper-locations: classpath*:mappers/*/*Mapping.xml,classpath*:mappers/*Mapping.xml

# 日志
logging:
  level:
    com.linbin: debug

# 系统监控
management:
  endpoints:
    web:
      exposure:
        include: health ,  metrics , info
